### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by jeckerman** [samuelm2/Nvidia-Notify#10]
Nice update! Noticed two minor issues:

https://github.com/samuelm2/Nvidia-Notify/blob/a6dfa0abda448e0507c4b2522d86d593f5668e31/notifier.py#L105-L124

Lines 105 and 124, `sms_notification()` need the `url` parameter 

Line 107, remove `time.`

It's great seeing all the attention it's getting since your reddit post yesterday, great work

**Comment by Kosyne** [comment]
Thanks for pointing that out! It should be fixed now. If you notice anything else, please don't hesitate to bring it up.
