### ISSUE TITLE
Ability to test twilio/discord integrations

### ISSUE THREAD

**Issue by Kosyne** [samuelm2/Nvidia-Notify#17]
Currently there's no way to verify if everything is set up correctly. Create an option, config, secondary script, or whatever it may be, that allows users to perform a test run of the notification options as configured in the .env file.

**Comment by LevytsRoman** [comment]
Good idea, for now you can put ```alert(url)``` on line 188 in notifier.py, this will bypass the checking logic and fire off the notify events,
hope it helps.( If it works don't forget to remove it tho)

**Comment by Kosyne** [comment]
Thanks for the assist! Went ahead and merged, I'll add it to the readme as well.
