### ISSUE TITLE
nvidia website gives false positives

### ISSUE THREAD

**Issue by samuelm2** [samuelm2/Nvidia-Notify#2]
recently the nvidia website started giving false positives. I haven't had time to figure out a way around these false positives, so if someone has time to figure it out and wants to submit a PR that'd be great

**Comment by Blake-Howard** [comment]
I was getting false positives on the 3080 search page, but am no longer when using main 3080 page on nvidia.

**Comment by Blake-Howard** [comment]
Picking up a false positive on best buy after the recent restock. cart.svg doesn't appear in the html. 

If that's replaced with the css classes for the active button it seems to work correctly again:
"btn btn-primary btn-sm btn-block btn-leading-ficon add-to-cart-button"

**Comment by EKMN** [comment]
One quite robust way could be to read directly from their store API.

Example below (5438481700 is the product ID for 3080)

GET `https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700`

```json
{
  "products": {
    "product": [
      {
        "id": 5438481700,
        "name": "NVIDIA GEFORCE RTX 3080 - US",
        "displayName": "NVIDIA GEFORCE RTX 3080",
        "sku": "900-1G133-2530-000",
        "displayableProduct": "false",
        "manufacturerPartNumber": "900-1G133-2530-000",
        "maximumQuantity": 1,
        "thumbnailImage": "https://drh1.img.digitalriver.com/DRHM/Storefront/Company/nvidia/images/product/thumbnail/geforce-rtx-3080-shop-thumbnail-100x100.png",
        "customAttributes": {
          "attribute": [
            {
              "name": "paypalOff",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "nonSolr",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "isGFNBundle",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "needsRestrictedShippingOption",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "shippingCountries",
              "type": "String",
              "value": "US,CA,PR,VI"
            },
            {
              "name": "shipmentAgreement",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "CategorySelection",
              "type": "String",
              "value": "Other"
            },
            {
              "name": "usps",
              "type": "String",
              "value": "false"
            },
            {
              "name": "additionalCartMessage",
              "type": "String",
              "value": "Limit 1 per customer"
            },
            {
              "name": "isGFN",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "preorderOverride",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "originalIsViewable",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "clonedFromStaging",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "landedCost",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "originalIsOrderable",
              "type": "Boolean",
              "value": "true"
            },
            {
              "name": "length",
              "type": "Quantity",
              "value": "357.000 mm"
            },
            {
              "name": "upc",
              "type": "String",
              "value": "812674024509"
            },
            {
              "name": "weight",
              "type": "Quantity",
              "value": "2.500 kg"
            },
            {
              "name": "disablePayPal",
              "type": "Boolean",
              "value": "true"
            },
            {
              "name": "hideInfo",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "hideQty",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "nvidiaPVDecoder",
              "type": "String",
              "value": "PureVideo Decoder Bronze"
            },
            {
              "name": "width",
              "type": "Quantity",
              "value": "166.000 mm"
            },
            {
              "name": "ProductDescription",
              "type": "String",
              "value": "GeForce"
            },
            {
              "name": "privateStoreOnly",
              "type": "Boolean",
              "value": "false"
            },
            {
              "name": "shipsInTimeFrameOverrideEnabled",
              "type": "Boolean",
              "value": "false"
            }
          ]
        },
        "pricing": {
          "uri": "https://dispatch-nvidia.digitalriver.com/v1/shoppers/me/products/5438481700/pricing",
          "listPrice": {
            "currency": "USD",
            "value": 699
          },
          "listPriceWithQuantity": {
            "currency": "USD",
            "value": 699
          },
          "salePriceWithQuantity": {
            "currency": "USD",
            "value": 699
          },
          "formattedListPrice": "$699.00",
          "formattedListPriceWithQuantity": "$699.00",
          "formattedSalePriceWithQuantity": "$699.00",
          "totalDiscountWithQuantity": {
            "currency": "USD",
            "value": 0
          },
          "formattedTotalDiscountWithQuantity": "$0.00",
          "listPriceIncludesTax": "false",
          "tax": {
            "vatPercentage": 0
          },
          "feePricing": {
            "salePriceWithFeesAndQuantity": {
              "currency": "USD",
              "value": 699
            },
            "formattedSalePriceWithFeesAndQuantity": "$699.00"
          }
        },
        "inventoryStatus": {
          "uri": "https://dispatch-nvidia.digitalriver.com/v1/shoppers/me/products/5438481700/inventory-status",
          "availableQuantityIsEstimated": "false",
          "productIsInStock": "true",
          "productIsAllowsBackorders": "false",
          "productIsTracked": "true",
          "requestedQuantityAvailable": "true",
          "status": "PRODUCT_INVENTORY_OUT_OF_STOCK",
          "statusIsEstimated": "false"
        },
        "relatedProducts": [
          {
            "id": 5440852400,
            "name": "GeForce NOW 1 Year Membership (RTX 30 Series Offer)",
            "image": "https://drh1.img.digitalriver.com/DRHM/Storefront/Company/nvidia/images/product/thumbnail/geforce-rtx-bundle-geforce-now-thumbnail-100x100.png"
          },
          {
            "id": 5440851900,
            "name": "Watch Dogs: Legion",
            "image": "https://drh1.img.digitalriver.com/DRHM/Storefront/Company/nvidia/images/product/thumbnail/geforce-rtx-bundle-watch-dogs-legion-thumbnail-100x100.png"
          }
        ],
        "viewStyle": "ampere"
      }
    ]
  }
}
```

The interesting bit there is this:

```json
{
   "inventoryStatus":{
      "uri":"https://dispatch-nvidia.digitalriver.com/v1/shoppers/me/products/5438481700/inventory-status",
      "availableQuantityIsEstimated":"false",
      "productIsInStock":"true",
      "productIsAllowsBackorders":"false",
      "productIsTracked":"true",
      "requestedQuantityAvailable":"true",
      "status":"PRODUCT_INVENTORY_OUT_OF_STOCK",
      "statusIsEstimated":"false"
   }
}
```

Specifically:

```json
{
  "status":"PRODUCT_INVENTORY_OUT_OF_STOCK",
}
```

**Comment by realalexgalenko** [comment]
this is what I did to get around nvidia false positives. Not ideal but it seems to be working... for now. Above approach is miles better. @EKMN how do I run GET in python? Thanks

`from urllib.request import urlopen, Request
from win10toast import ToastNotifier
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

import webbrowser
import time
import random
from datetime import datetime

from twilio.rest import Client


'''
Template for adding a new website to check:
The key is the url of the website you want to check
The Value is a tuple of size 4 with the following values:
    0. The substring that you're looking for in the html of the website
    1. If this is True, it will alert when the substring is found in the html. If False, it will alert if the substring is NOT found in the HTML
    2. If this is True, it will use Selenium/FireFox to get the HTML from the website. This is useful when a website is a jsx page instead of static HTML (ex. BestBuy).
    3. A nickname for the alert to use.
'''
urlKeyWords = {
    #"https://www.nvidia.com/en-us/geforce/graphics-cards/rtx-2060-super/" : ("AdD To cart", True, True, 'Nvidia'),
    #"https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3080/" : ("Out Of Stock", False, True, 'Nvidia'),
    "https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3080/" : ("Add to cart", True, True, 'Nvidia'),
    
    "https://www.evga.com/products/productlist.aspx?type=0&family=GeForce+30+Series+Family&chipset=RTX+3080" : ("AddCart", True, False, 'EVGA'),
    # "https://www.evga.com/products/productlist.aspx?type=0&family=GeForce+16+Series+Family&chipset=GTX+1650+Super" : ("AddCart", True, False, 'EVGATest'),
    "https://www.newegg.com/p/pl?d=rtx+3080&N=100007709%20601357247" : ("Add to cart", True, False, 'Newegg'),
    "https://www.bhphotovideo.com/c/search?q=3080&filters=fct_category%3Agraphic_cards_6567" : ("Add to Cart", True, False, 'BandH'),
    "https://www.bestbuy.com/site/searchpage.jsp?st=3080" : ("cart.svg", True, True, "BestBuy"),
    # "https://www.bestbuy.com/site/searchpage.jsp?st=tv" : ("cart.svg", True, True, "BestBuyTest")
    "https://www.amazon.com/stores/page/6B204EA4-AAAC-4776-82B1-D7C3BD9DDC82?ingress=0" : (">Add to Cart<", True, False, 'Amazon')
    # "https://store.asus.com/us/item/202009AM160000001" : (">Buy Now<", True, False, 'ASUS')
}

# Download the geckodriver from https://github.com/mozilla/geckodriver/releases, and then put the path to the executable in this rstring.
# I used version 0.27.0
firefoxWebdriverExecutablePath = r'C:\geckodriver.exe'

# If you want text notifications, you'll need to have a Twilio account set up (Free Trial is fine)
# Both of these numbers should be strings, in the format '+11234567890' (Not that it includes country code)
twilioToNumber = '+1xxxxxxxxxx'
twilioFromNumber = '+1xxxxxxxxxx'
twilioSid =  'XXXXXX'
twilioAuth = 'YYYYY'
client = Client(twilioSid, twilioAuth)


options = Options()
options.headless = True
toast = ToastNotifier()
driver = webdriver.Firefox(options=options, executable_path=firefoxWebdriverExecutablePath)
numReloads = 0

def alert(url):
    print("3080 IN STOCK")
    print(url)
    webbrowser.open(url, new=1)
    toast.show_toast("3080 IN STOCK", url, duration=5, icon_path="icon.ico")
    #message = client.messages.create(to=twilioToNumber, from_=twilioFromNumber, body=url)
    print("taking some rest....")
    time.sleep(200)

def seleniumGet(url):
    # for jsp sites
    # test url : https://www.bestbuy.com/site/searchpage.jsp?st=3080 
    global driver
    global numReloads

    driver.get(url)
    http = driver.page_source

    numReloads += 1
    if numReloads == 10:
        numReloads = 0
        driver.close()
        driver.quit()
        driver = webdriver.Firefox(options=options, executable_path=firefoxWebdriverExecutablePath)
    return http

def urllibGet(url):
    # for regular sites
    # Fake a Firefox client
    request = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    page = urlopen(request, timeout=30)
    html_bytes = page.read()
    html = html_bytes.decode("utf-8")
    return html

def got_stock(url, info):
    try:
        if info[2]:
            html = seleniumGet(url)
        else:
            html = urllibGet(url)
    except Exception as e:
        print("Connection failed...")
        print(e)
        return False
    keyWord = info[0]
    alertOnFound = info[1]
    index = html.find(keyWord)
    index = html.upper().find(keyWord.upper())
    gotStock=False
    if alertOnFound and index != -1 and "show-out-of-stock" not in html[index-150:index+150]:
        print(index)
        print(html[index-150:index+150])
        #alert(url)
        gotStock = True
    elif not alertOnFound and index == -1:
        #print(html[index-50:index+50])
        gotStock = True
    return gotStock

def main():
    numSearches = 0
    while True:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print("Starting search {} at {}".format(numSearches, current_time))
        numSearches += 1
        for url, info in urlKeyWords.items():
            print("\tChecking {}...".format(info[3]))
            if got_stock(url, info):
                print("........confirming in stock signal")
                baseSleepAmt = 1
                totalSleep = baseSleepAmt + random.uniform(0, 4)
                time.sleep(totalSleep)
                if got_stock(url, info):
                    alert(url)
        baseSleepAmt = 1
        totalSleep = baseSleepAmt + random.uniform(6, 20)
        # print("Sleeping for {} seconds".format(totalSleep))
        time.sleep(totalSleep)


if __name__ == '__main__':
    main()`

**Comment by dereckhall** [comment]
how often are you guys getting them?

under def seleniumGet i added:
    driver.set_page_load_timeout(60)

so far so good. so it either helped, or i've just been extremely lucky.

i've also adjusted the sleep timings as i didn't want to get IP banned by nvidia/bbuy etc.
        baseSleepAmt = 30
        totalSleep = baseSleepAmt + random.uniform(0, 10)

**Comment by realalexgalenko** [comment]
@dereckhall 
bestbuy - havent gotten any yet
nvidia - was getting it on every 10-ish request. Now it was running for 2 hours no issues. 

Good point on ban, would suck to also switch vpn every now and then. Might increase wait time to be a little longer

**Comment by EKMN** [comment]
> this is what I did to get around nvidia false positives. Not ideal but it seems to be working... for now. Above approach is miles better. @EKMN how do I run GET in python? Thanks
> 
> ```python
> def got_stock(url, info):
>     try:
>         if info[2]:
>             html = seleniumGet(url)
>         else:
>             html = urllibGet(url)
>     except Exception as e:
>         print("Connection failed...")
>         print(e)
>         return False
>     keyWord = info[0]
>     alertOnFound = info[1]
>     index = html.find(keyWord)
>     index = html.upper().find(keyWord.upper())
>     gotStock=False
>     if alertOnFound and index != -1 and "show-out-of-stock" not in html[index-150:index+150]:
>         print(index)
>         print(html[index-150:index+150])
>         #alert(url)
>         gotStock = True
>     elif not alertOnFound and index == -1:
>         #print(html[index-50:index+50])
>         gotStock = True
>     return gotStock
> 
> def main():
>     numSearches = 0
>     while True:
>         now = datetime.now()
>         current_time = now.strftime("%H:%M:%S")
>         print("Starting search {} at {}".format(numSearches, current_time))
>         numSearches += 1
>         for url, info in urlKeyWords.items():
>             print("\tChecking {}...".format(info[3]))
>             if got_stock(url, info):
>                 print("........confirming in stock signal")
>                 baseSleepAmt = 1
>                 totalSleep = baseSleepAmt + random.uniform(0, 4)
>                 time.sleep(totalSleep)
>                 if got_stock(url, info):
>                     alert(url)
>         baseSleepAmt = 1
>         totalSleep = baseSleepAmt + random.uniform(6, 20)
>         # print("Sleeping for {} seconds".format(totalSleep))
>         time.sleep(totalSleep)
> 
> 
> if __name__ == '__main__':
>     main()
> ```

You can basically use any request library that makes a GET request (usually the default option). Then parse the JSON response and evaluate the key-value pair that I highlighted.

**Comment by ItsCalebJones** [comment]
```
        response = requests.get("https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700")
        item = response.json()

        print(item['products']['product'][0]['inventoryStatus']['status'])
        if item['products']['product'][0]['inventoryStatus']['status'] != "PRODUCT_INVENTORY_OUT_OF_STOCK":
            alert("Nvidia API")
```

**Comment by zzoth** [comment]
Quick and dirty steps to switch to API calls:

Add the following import:
```
import requests
from requests.exceptions import HTTPError
```

I just put this in main() and removed the loop over urlKeywords since I was only interested in the FE from the Nvidia site. I'm still using alert() with the Nvidia URL for toasts and notifications.

```
response = requests.get('https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700')
jsonResponse = response.json()
stock = jsonResponse["products"]["product"][0]["inventoryStatus"]["status"]
print(stock)
if (stock != "PRODUCT_INVENTORY_OUT_OF_STOCK") :
    alert("https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3080/")
```

**Comment by ItsCalebJones** [comment]
Try this:

```Python
def got_stock(url, info):
    try:
        if info[2]:
            html = seleniumGet(url)
        else:
            html = urllibGet(url)
    except Exception as e:
        print("Connection failed...")
        print(e)
        return False
    keyWord = info[0]
    alertOnFound = info[1]
    index = html.find(keyWord)
    index = html.upper().find(keyWord.upper())
    gotStock=False
    if alertOnFound and index != -1 and "show-out-of-stock" not in html[index-150:index+150]:
        print(index)
        print(html[index-150:index+150])
        #alert(url)
        gotStock = True
    elif not alertOnFound and index == -1:
        #print(html[index-50:index+50])
        gotStock = True
    return gotStock


def check_nvidia_api():
    response = requests.get("https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700")
    item = response.json()
    print(item['products']['product'][0]['inventoryStatus']['status'])
    if item['products']['product'][0]['inventoryStatus']['status'] != "PRODUCT_INVENTORY_OUT_OF_STOCK":
        return True
    else:
        return False


def main():
    numSearches = 0
    toast.show_toast("Hello World!!!",
                       "Python is 10 seconds awsm!",
                       icon_path="icon.ico",
                       duration=10)
    while True:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print("Starting search {} at {}".format(numSearches, current_time))
        numSearches += 1
        for url, info in urlKeyWords.items():
            print("\tChecking {}...".format(info[3]))
            if got_stock(url, info):
                print("........confirming in stock signal")
                baseSleepAmt = 1
                totalSleep = baseSleepAmt + random.uniform(2, 10)
                time.sleep(totalSleep)
                if got_stock(url, info):
                    if info[4] == "Nvidia":
                        if check_nvidia_api():
                            alert(url)
                else:
                    alert(url)

        baseSleepAmt = 1
        totalSleep = baseSleepAmt + random.uniform(2, 15)
        # print("Sleeping for {} seconds".format(totalSleep))
        time.sleep(totalSleep)


if __name__ == '__main__':
    main()
```

**Comment by realalexgalenko** [comment]
@ItsCalebJones i ended up at the same code, just moved 
```
   else:
       alert(url) 
```
to make it for if info[4] == "Nvidia": statement

**Comment by ItsCalebJones** [comment]
That was a derp ;)

**Comment by Kosyne** [comment]
Submitted #5 , should handle grabbing nvidia stuff by API instead of by html, and has a few other QOL changes.

**Comment by samuelm2** [comment]
Gonna close this out. Thanks for ironing this out, all!
