### ISSUE TITLE
Nvidia API URL no longer working

### ISSUE THREAD

**Issue by gesworthy** [samuelm2/Nvidia-Notify#21]
The Nvidia API URL is timing out and not working.

Hard to tell if they moved it or is just temporarily down?

    Checking Nvidia 3080...
		Connection failed...
		HTTPSConnectionPool(host='api-prod.nvidia.com', port=443): Read timed out. (read timeout=5)

Looks like on their own site they are using the same URL and the call is timing out there as well. So likely an Nvidia problem.

**Comment by Kosyne** [comment]
Check pinned issues.

**Comment by gesworthy** [comment]
Ah, sorry, completely missed the pinned issue :)
