### ISSUE TITLE
Documentation for new JSON Site List

### ISSUE THREAD

**Issue by Kosyne** [samuelm2/Nvidia-Notify#22]
Update the readme with information regarding the new way we handle adding to the site list.

Refer to this merge for more info #11

**Comment by jeckerman** [comment]
It's only fair that I do this

Regret changing `substring` to `keyword`, it makes far more sense as the former.  :man_facepalming:

The PR #24

**Comment by Kosyne** [comment]
Thanks for your time working on this. Also, no problem, it's just a quick useful script that'll probably fade into obscurity after the whole scarcity thing passes, so minor stuff like that isn't too big of a deal so long as it makes some kind of sense.
