### ISSUE TITLE
On Mac, python3 /path/notifier.py returns error.

### ISSUE THREAD

**Issue by simonfalke-01** [samuelm2/Nvidia-Notify#41]
With `python3 /Users/[user]/Downloads/Nvidia-Notify-master/notifier.py`

terminal returns 
```
Traceback (most recent call last):
  File "/Users/brandonli/Downloads/Nvidia-Notify-master/notifier.py", line 40, in <module>
    with open('sites.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sites.json'
```
Is there a fix for it? Thanks.

Edit: I do have the file sites.json in the Nvidia-Notify directory. The folder was `git` cloned.

**Comment by daEdward** [comment]
Try calling the script from the working directory...

```
cd /Users/[user]/Downloads/Nvidia-Notify-master
python3 notifier.py
```
