### ISSUE TITLE
Not an issue - question regarding code

### ISSUE THREAD

**Issue by RichardMisencik** [samuelm2/Nvidia-Notify#42]
Not an issue, hope it's okay to ask here, i'm beginner in python but can someone please explain what is the purpose of this code from notifier.py starting at line 205? i understand the first if statement but why the second one does the same thing (send alert)?:

```
if alert_on_found and index != -1:
    alert(site)
elif not alert_on_found and index == -1:
    alert(site)
```

**Comment by aabodei** [comment]
If the alert on found is set to false for the specified site, that means it is looking for a word that is not there. If index returns -1, which means nothing was found, it will send an alert.

Refer to the configuration table. Find the 'alert' field and its corresponding description.

That should explain it!

**Comment by RichardMisencik** [comment]
I'm so dumb, thanks for the explanation and pointing me to the config table (I missed the description)!
